services:
  mysql:
    image: mysql:8
    container_name: ems-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ems
    ports:
      - "3308:3306"
    networks:
      - ems-network

  backend:
    build:
      context: ./ems-backend
      dockerfile: Dockerfile
    image: employee_backend:v1
    container_name: employee-backend
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    networks:
      - ems-network

  frontend:
    build:
      context: ./ems-frontend
      dockerfile: Dockerfile
    image: employee_frontend:v1
    container_name: employee-frontend
    restart: unless-stopped
    ports:
      - "8085:80"
    depends_on:
      - backend
    networks:
      - ems-network

networks:
  ems-network:
    driver: bridge
